- name: nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_20.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: app preq
  ansible.builtin.import_tasks: app-preq.yml



- name: download dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: schema setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined


- name: setup {{component}}
  ansible.builtin.import_tasks: systemd.yml


#    - name: Check nodejs is installed
#      ansible.builtin.shell: type npm
#      register: command_status
#      ignore_errors: yes
#
#    - name: INstall NodeJS Repos
#      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
#      when: command_status.rc != 0
#
#    - name: Install NodeJS
#      ansible.builtin.yum:
#        name: nodejs
#        state: installed
#      when: command_status.rc != 0
#
#    - name: App Pre-requisites
#      ansible.builtin.import_tasks: app-preq.yml
#
#    #- name: Download NodeJS Dependencies
#    #  ansible.builtin.shell: npm install
#    #  args:
#    #    chdir: /app
#
#    - name: Schema Setup
#      ansible.builtin.import_tasks: mongo-schema.yml
#      when: schema is defined
#
#    - name: SystemD Setup
#      ansible.builtin.import_tasks: systemd-setup.yml