- name: setup systemd
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/{{component}}.service


- name: start {{component}} service
  ansible.builtin.systemd:
    name: {{component}}
    state: intalled
    enabled: yes
    daemon_reload: yes